config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  resources :college_classes
  resources :users
  resources :sessions
  
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  get 'signup', to: 'users#new', as: :signup
  
  get 'home/index' => 'home#index', as: :home
  get 'home/submit_search' => 'home#submit_search'
  post 'home/submit_search' => 'home#submit_search'
  root 'home#index'
    
end

app/models/college_class.rb
class CollegeClass < ActiveRecord::Base
	has_many :posts,:foreign_key => 'course_number', :primary_key => 'course_number'
end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :college_class,:foreign_key => 'course_number', :primary_key => 'course_number'
validate :course_id_must_exist

  def course_id_must_exist
  all_course_numbers = CollegeClass.all.map{|cur_class| cur_class.course_number}
    if(!all_course_numbers.include?(course_number))
       errors.add(:course_number, "That course number does not exist")
  	end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password
  
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+cmu.edu)\z/i, message: "is not a CMU email"
  
  validates_presence_of :password, on: :create 
  validates_presence_of :password_confirmation, on: :create
  validates_confirmation_of :password, message: "does not match"
  validates_length_of :password, minimum: 6, message: "must be at least 6 characters long", allow_blank: true
  
  validates_presence_of :first_name
  validates_presence_of :last_name
  
  validates_numericality_of :grad_year
  
  def self.authenticate(email, password)
    find_by_username(email).try(:authenticate, password)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def logged_in?
    current_user
  end
  helper_method :logged_in?

  def check_login
    redirect_to login_url, alert: "Permission Denied" if current_user.nil?
  end
  
end

app/controllers/college_classes_controller.rb
class CollegeClassesController < ApplicationController
  before_action :set_college_class, only: [:show, :edit, :update, :destroy]

  # GET /college_classes
  # GET /college_classes.json
  def index
    @college_classes = CollegeClass.all
  end

  # GET /college_classes/1
  # GET /college_classes/1.json
  def show
    @post = Post.new
  end

  # GET /college_classes/new
  def new
    @college_class = CollegeClass.new
    @post = Post.new
  end

  # GET /college_classes/1/edit
  def edit
  end

  # POST /college_classes
  # POST /college_classes.json
  def create
    @college_class = CollegeClass.new(college_class_params)

    respond_to do |format|
      if @college_class.save
        format.html { redirect_to @college_class, notice: 'College class was successfully created.' }
        format.json { render :show, status: :created, location: @college_class }
      else
        format.html { render :new }
        format.json { render json: @college_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /college_classes/1
  # PATCH/PUT /college_classes/1.json
  def update
    respond_to do |format|
      if @college_class.update(college_class_params)
        format.html { redirect_to @college_class, notice: 'College class was successfully updated.' }
        format.json { render :show, status: :ok, location: @college_class }
      else
        format.html { render :edit }
        format.json { render json: @college_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /college_classes/1
  # DELETE /college_classes/1.json
  def destroy
    @college_class.destroy
    respond_to do |format|
      format.html { redirect_to college_classes_url, notice: 'College class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college_class
      @college_class = CollegeClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_class_params
      params.require(:college_class).permit(:name, :department, :course_number, :units)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@post = Post.new
  end

  def submit_search
  course_number = params[:course_number]
  @searched_class = CollegeClass.find_by course_number: course_number
  @post = Post.new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    if(@post.save)
      redirect_to :controller => 'home', :action => 'submit_search', :course_number => @post.course_number
    else
      render :action=>'new'
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:course_number, :instructor, :comment, :semester, :year)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_path, notice: "Logged In"
    else
      flash.now.alert = "Email or Password Invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :check_login, except: [:new, :create]
  
  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to home_path
    else
      render :action => "new"
    end
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      redirect_to home_path
    else
      render :action => "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :grad_year)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/college_classes_helper.rb
module CollegeClassesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/college_classes/_form.html.erb
<%= form_for(@college_class) do |f| %>
  <% if @college_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@college_class.errors.count, "error") %> prohibited this college_class from being saved:</h2>

      <ul>
      <% @college_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :course_number %><br>
    <%= f.text_field :course_number %>
  </div>
  <div class="field">
    <%= f.label :units %><br>
    <%= f.number_field :units %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/college_classes/edit.html.erb
<h1>Editing College Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @college_class %> |
<%= link_to 'Back', college_classes_path %>

app/views/college_classes/index.html.erb
<%= render '/home/home' %>

<p id="notice"><%= notice %></p>

<h1>Listing College Classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th>Number</th>
      <th>Units</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @college_classes.each do |college_class| %>
      <tr>
        <td><%= college_class.name %></td>
        <td><%= college_class.department %></td>
        <td><%= college_class.course_number %></td>
        <td><%= college_class.units %></td>
        <td><%= link_to 'Show', college_class %></td>
        <td><%= link_to 'Edit', edit_college_class_path(college_class) %></td>
        <td><%= link_to 'Destroy', college_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College class', new_college_class_path %>

<%= render '/home/footer' %>

app/views/college_classes/new.html.erb
<h1>New College Class</h1>

<%= render 'form' %>

<%= link_to 'Back', college_classes_path %>

app/views/college_classes/show.html.erb
<%= render '/home/home' %>

<div id="content">
	<h2>
	  <%= @college_class.course_number %> <%= @college_class.name %>
	</h2>

	<h4>
	  <%= @college_class.department %> Department<br>
	  <%= @college_class.units %> Units
	</h4>

	<div id="comments">
		<%= render '/posts/comments' %>
	</div>

	<div id="newpost">
		<%= link_to 'Tell us about your experience!', new_post_path, class: 'btn-default' %>
		<%= render '/posts/form' %>
	</div>
	
</div>




<%#= link_to 'Edit', edit_college_class_path(@college_class) %> 
<%#= link_to 'Back', college_classes_path %>

app/views/home/_footer.html.erb
<div
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://github.com/nielsenius/course-intel/">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; 2015</p>
                </div>
            </div>
        </div>
    </footer>

app/views/home/_home.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Course Intel</title>

    <!-- Bootstrap Core CSS -->
    <!-- <link href="/assets/stylesheets/bootstrap.css" rel="stylesheet"> -->

    <!-- Custom CSS -->
    <link href="/assets/stylesheets/course-intel.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <div id="logo">
                            <%= link_to 'index' do %>
                                <%= image_tag('logo-01.png') %>
                                <% end %>
                        </div>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <div id="auth-buttons">
                        <div id="auth-button">
                            <% if logged_in? %>
                                <%= link_to "Logout", logout_path, :class => "btn-default" %>
                            <% else %>
                                <%= link_to "Login", login_path, :class => "btn-default" %>
                                <%= link_to "Sign Up", signup_path, :class => "btn-default" %>
                            <% end %>
                        </div>
                    </div>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Get the latest intel.</h1>
                        <hr class="small">
                        <div id="search">
                            <%= form_tag '/home/submit_search' do %>
                            <%=text_field_tag 'course_number', nil, placeholder: 'Search for a course i.e. 67-475...', size: 50 %>
                            <%= button_tag 'Search', class: 'btn btn-default' %>
                        </div>

                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/clean-blog.min.js"></script>

</body>

</html>

app/views/home/index.html.erb
<%= render '/home/home' %>
<%= render '/home/footer' %>

app/views/home/submit_search.html.erb
<%= render '/home/home' %>

<div id="content">
  <% if(@searched_class) %>
	<h2>
	  <%= @searched_class.course_number %> <%= @searched_class.name %>
	</h2>

	<h4>
	  <%= @searched_class.department %> Department<br>
	  <%= @searched_class.units %> Units
	</h4>

	<div id="comments">
		<%= render '/posts/comments' %>
	</div>
  <%else %>
    <h3> No posts exist for this class</h3>
  <% end %>

	
	<% if logged_in? %>
		<div id="newpost">
			<h4>Have you taken this course?</h4>
			<%= render '/posts/form' %>
		</div>
	<% end %>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseIntel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_comments.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h4>What past students have to say:</h4>

<ul>
  <% @searched_class.posts.each do |post| %>
    <li>
      <%= post.comment %><br>
      <em>Semester: <%= post.semester %> <%= post.year %> &nbsp;&nbsp;&nbsp;Professor: <%= post.instructor %></em>
      <br><br>
    </li>
  <% end %>
</ul>


<br>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>

<div class="row">
  <div class="col-md-12">
    <%= f.input :course_number, placeholder: 'i.e. 67475' %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= f.input :instructor, placeholder: 'i.e. Heimann' %>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <%= f.input :semester, as: :radio_buttons,
    collection: ['Fall', 'Spring', 'Summer'] %>
  </div>
  <div class="col-md-6">
    <%= f.input :year, :collection => (2000..2015).to_a.reverse %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= f.input :comment, placeholder: 'Tell us about your experience in this course' %>
  </div>
</div>
  <%= f.button :submit, "Post Comment", class: 'btn-default' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Class</th>
      <th>Instructor</th>
      <th>Comment</th>
      <th>Semester</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.course_number %></td>
        <td><%= post.instructor %></td>
        <td><%= post.comment %></td>
        <td><%= post.semester %></td>
        <td><%= post.year %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Class:</strong>
  <%= @post.class_id %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @post.instructor %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @post.comment %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @post.semester %>
</p>

<p>
  <strong>Year:</strong>
  <%= @post.year %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<!-- Custom CSS -->
<link href="/assets/stylesheets/course-intel.css" rel="stylesheet">

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :grad_year %><br />
    <%= f.text_field :grad_year %>
  </p>
  
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/edit.html.erb
<h3>Update User</h3>

<%= render 'form' %>

app/views/users/new.html.erb
<h3>Sign Up</h3>

<p>Already have an account? <%= link_to "Log In", login_path %>.</p>

<%= render 'form' %>